### PR TITLE
Fixed

### PR DESCRIPTION
**Pull request by KannaAny**

### CODE REVIEW

**Review by ignassew — APPROVED** [review]

**Comment by KannaAny** [comment]
Are the two new apps I added causing problems? Weird, I really don't understand Git much

**Comment by ignassew** [comment]
Well now it's got conflicts 😅

**Comment by KannaAny** [comment]
> Well now it's got conflicts 😅

Yes, the two new apps I added, I don't see anything wrong with them, how strange haha

**Comment by ignassew** [comment]
> Are the two new apps I added causing problems? Weird, I really don't understand Git much

It's the difference between the main branch and your branch. The main branch had some changes that your branch didn't.

Try creating a new branch, make sure it's up to date with origin/main and then add your changes.

**Pull request closed without merging**
