### PR TITLE
Add new apps

### PR DESCRIPTION
**Pull request by KannaAny**

### CODE REVIEW

**Comment by ignassew** [comment]
Please resolve the conflicts, thanks for contributing!

**Comment by ignassew** [comment]
Thanks for contributing.

Please resolve the conflicts and I will merge it.

**Comment by KannaAny** [comment]
Ready

**Comment by ignassew** [comment]
@KannaAny now the markdown table isn't rendering.

**Comment by ignassew** [comment]
I had to revert it

**Pull request merged**
